import { StyleSheet } from 'react-native';

const Styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F7F7F7',
    },
    header: {
        height: 250,
        backgroundColor: '#E0323C',
        borderBottomLeftRadius: 160,
        borderBottomRightRadius: 160,
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingTop: 18,
        position: 'relative',
    },
    navButton: {
        position: 'absolute',
        top: 52,
        width: 56,
        height: 56,
        borderRadius: 14,
        backgroundColor: 'rgba(255,255,255,0.18)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    navButtonLeft: {
        left: 20,
    },
    navButtonRight: {
        right: 20,
    },
    headerIconContainer: {
        width: 128,
        height: 128,
        borderRadius: 64,
        backgroundColor: '#FFF',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 52,
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 8 },
        elevation: 6,
    },
    headerImage: {
        width: 72,
        height: 72,
        tintColor: '#E0323C',
    },
    content: {
        flex: 1,
        marginTop: -20,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 24,
    },
    questionCard: {
        backgroundColor: '#FFF',
        borderRadius: 24,
        paddingVertical: 24,
        paddingHorizontal: 22,
        minHeight: 380,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 10 },
        elevation: 4,
        justifyContent: 'space-between',
    },
    questionIndex: {
        fontSize: 14,
        color: '#555',
        fontWeight: '800',
        marginBottom: 10,
    },
    questionText: {
        fontSize: 20,
        lineHeight: 28,
        color: '#333',
        fontWeight: '700',
        textAlign: 'left',
    },
    booleanActions: {
        width: '100%',
        gap: 18,
        marginTop: 28,
    },
    answerButton: {
        width: '100%',
        height: 58,
        borderRadius: 28,
        borderWidth: 1,
        borderColor: '#E0323C',
        backgroundColor: '#FFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    answerButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#444',
    },
    choiceList: {
        width: '100%',
        marginTop: 28,
        gap: 14,
    },
    choiceSelectBlock: {
        width: '100%',
        marginTop: 20,
    },
    choiceSelectIconRow: {
        alignItems: 'flex-end',
        marginBottom: 10,
    },
    choiceSelectField: {
        width: '100%',
        height: 58,
        borderRadius: 28,
        borderWidth: 1,
        borderColor: '#E0323C',
        backgroundColor: '#FFF',
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    choiceSelectFieldText: {
        fontSize: 15,
        color: '#777',
        flex: 1,
    },
    choiceSelectDropdown: {
        marginTop: 12,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#F1B6BC',
        overflow: 'hidden',
    },
    choiceSelectItem: {
        paddingVertical: 14,
        paddingHorizontal: 16,
        backgroundColor: '#FFF',
        borderBottomWidth: 1,
        borderBottomColor: '#F3F3F3',
    },
    choiceSelectItemText: {
        fontSize: 15,
        color: '#333',
        fontWeight: '600',
    },
    choiceButton: {
        width: '100%',
        minHeight: 54,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#E0323C',
        backgroundColor: '#FFF',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
    },
    choiceButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#333',
        textAlign: 'center',
    },
    inputArea: {
        marginTop: 22,
    },
    monthConfirmText: {
        fontSize: 18,
        lineHeight: 26,
        color: '#333',
        fontWeight: '700',
        marginBottom: 18,
    },
    radioList: {
        marginTop: 16,
        gap: 10,
    },
    radioRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    radioCircle: {
        width: 12,
        height: 12,
        borderRadius: 6,
        borderWidth: 1.5,
        borderColor: '#E0323C',
    },
    radioCircleActive: {
        backgroundColor: '#E0323C',
    },
    radioLabel: {
        fontSize: 14,
        color: '#444',
    },
    nextButton: {
        marginTop: 14,
        height: 54,
        borderRadius: 28,
        backgroundColor: '#E0323C',
        alignItems: 'center',
        justifyContent: 'center',
    },
    nextButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: '800',
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.45)',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    modalCard: {
        width: '100%',
        backgroundColor: '#FFF',
        borderRadius: 24,
        padding: 24,
        alignItems: 'center',
        gap: 12,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#333',
        textAlign: 'center',
    },
    modalMessage: {
        fontSize: 15,
        lineHeight: 22,
        color: '#666',
        textAlign: 'center',
        marginBottom: 8,
    },
});

export default Styles;